services:
  - type: web
    name: hk-immigration-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    corsOrigins: "*"
